baseURL = "https://w-tiecoop.co.kr/"
languageCode = "ko-ko	"
title = "더블유타이(W-tie)협동조합"
description = "더블유타이(W-tie)협동조합은 사회적 가치를 생산하는 모든 사람이 일과 생활의 균형감각을 유지하고 자기 결정원을 회복할 수 있도록 일생활균형 실천의 일상화.생활화를 위해 회원들의 전문성을 살려 삶의 평범함을 모델로 민주적인 조직문화 변화 솔루션 개발과 교육.문화 운동에 전문화와 일거리 등 조합원의 지속가능한 자립을 돕는 기회 나눔을 시도합니다."

[permalinks]
  blog = "/:filename/"

[params]
	homeText = "you just made W-tie coop homepage"